### ISSUE TITLE
how to hide a fold?

### ISSUE THREAD

**Issue by b1gdea1** [Y-Ysss/Hello-NewTab#1]
in previous project, i can use a " ' " to hide a fold, but now i cannot do it.

**Comment by yuyosy** [comment]
Thank you for using the project.
Since I'm Japanese I am bad at English.

In the release of [version 0.6](https://github.com/Y-Ysss/Hello-NewTab/releases/tag/v0.6) (Commit: 97657e5), it has been fixed 0d20dfb so that the folder name starts with `'` can be switched between hidden/visible.

Try it. If there is a problem, please start Issue.

**Note:**
Currently, extension cannot convert old options format to new ones, so please remove the extension and then install the new version.

**In the future:**
- The function that can set the regex pattern is implemented in the code.
- However, the input field of regex pattern is disabled because the process to invalidate the inappropriate character string entered by the user is not implemented.

**Comment by b1gdea1** [comment]
so thanks. problem solved perfectly.
